[ORIGENDATO]SQL
[SOURCETYPE]ADO
[USERNAME]ç|
[PWDNAME]]ÅOQVT
[WEBSERVICE]
[PATHDATABASE]
[PWDLEN]6
[USERLEN]2


[SERVENAME]mildeliciasfao.ddns.net\sql2014,1170
[INITCATALOGO]mildelicias
[SUCURSAL]9

#[SERVENAME]mildeliciasne.ddns.net\sql2014,1171
#[INITCATALOGO]mildelicias
#[SUCURSAL]1

#[SERVENAME]marcos-hp\sql2022

#[INITCATALOGO]mildelicias_mitre
#[SUCURSAL]3

#[INITCATALOGO]mildelicias_fab
#[SUCURSAL]4

#[INITCATALOGO]mildelicias_bel
#[SUCURSAL]5

#[INITCATALOGO]mildelicias_alsina
#[SUCURSAL]6