[ORIGENDATO]SQL
[SOURCETYPE]ADO
[USERNAME]ç|
[PWDNAME]]ÅOQVT
[WEBSERVICE]
[PATHDATABASE]
[PWDLEN]6
[USERLEN]2

#[SERVENAME]marcos\sql2019
[SERVENAME]meridiem.ddns.net\sql2019,1170
[SUCURSAL]1
[INITCATALOGO]meridiem
