goapp.idejercicio = 1100000027
goapp.terminal = 12&&22 &&4 &&22
goapp.idusuario = 1
*goapp.codempresa = 1
goapp.sucursal =1
goapp.switchusuario = '11100'
oavisar.usuario('goapp.idejercicio = '+LTRIM(STR(goapp.idejercicio))+CHR(13);
				+'GOAPP.SUCURSAL10 = '+STR(GOAPP.SUCURSAL10)+CHR(13);
				+'Goapp.terminal =' + STR(goapp.terminal))