use gestion
go
delete from cuerfac
delete from movstock
delete from ncuerfac
delete from tablaasi
delete from dcuerfac
delete from tablaimp
delete from maopera
delete from cabefac
delete from renmaope
delete from cabeasi
delete from fletecarga
delete from afenpedido
delete from ncabefac
delete from nmaopera	
delete from afedmaope
delete from dmaopera
delete from dcabefac
delete from dcabedeta
delete from dpagos
delete from prodctacon
delete from movctacte
delete from cbioprecio
delete from movcaja
delete from fleteren
delete from	renflete
delete from alertas
delete from cuerruta
delete from afectacte
delete from cuervari
delete from cabedeta
delete from ctactectacon
delete from ncuervari
delete from pedipda
delete from visita
delete from cabecpra
delete from fleteplanilla
delete from afelicita
delete from dcuervari
delete from gestion
delete from anmaopera
delete from existenc
delete from producto
delete from plancue_aux
delete from ctacte
delete from movpub
delete from movtarjeta
delete from detanrocaja
delete from afecabefac
delete from movbcocar
delete from movbcodeta
delete from MovLicita
delete from cuerord
delete from caberuta
delete from afeasto
delete from sucursal
delete from renctacte
delete from bloqueoprod
delete from cuermod
delete from ctacte_2
delete from subproducto
delete from ruta
delete from rutavdor
delete from cabemod
delete from zonaruta
delete from idasociado
delete from cabeord
delete from cotizadolar
delete from afebcocar
delete from rubro
delete from barrio
delete from zona
delete from fletero
delete from ctacteflete
delete from cuervariord
delete from vendedor
delete from cuerunifica
DELETE FROM ctactemod
--DELETE FROM BANCO	
DELETE FROM BONIVDOR
DELETE FROM MARCA
DELETE FROM cabeunifica
delete from cabepromo
delete from gruposcomi

delete from cuervariord
delete from movbcodeta
delete from afebcocar
delete from ctacte_2
delete from prodcodbarra
delete from renctacte
delete from movpub
delete from idasociado
delete from cuercombo
delete from cabecombo

execute actualizarid 1
select * from keysid order by nextid desc