[ORIGENDATO]SQL
[SOURCETYPE]ADO
[SERVENAME]frigorificosur-server\sql2014,1170
#[SERVENAME]marcos-hp\sql2022
[INITCATALOGO]ptovta
[USERNAME]ç|
[PWDNAME]]ÅOQVT
[WEBSERVICE]
[PATHDATABASE]
[SUCURSAL]1
[PWDLEN]6
[USERLEN]2
