// clientes.js - Datos de clientes para el mapa (sin CORS)
window.clientesData = [
    {
        "num": "14",
        "coords": [-38.728117, -62.299745],
        "nombre": "LIN YUJIE",
        "direccion": "SANTA CRUZ 952",
        "alt": "1100000012",
        "activo": true,
        "fecha_alta": "2022-05-20",
        "tipo_negocio": "particular",
        "estado_cuenta": "al_dia",
        "categoria_cliente": "silver",
        "canal_venta": "presencial",
        "zona_geografica": "centro",
        "telefono": "+54 291 123-4567",
        "email": "lin.yujie@email.com",
        "vendedor": "Carlos Rodriguez"
    },
    {
        "num": "100",
        "coords": [-38.741441, -62.269791],
        "nombre": "AGUIRRE HNOS. SRL",
        "direccion": "PAUNERO 1130",
        "alt": "1100000091",
        "activo": true,
        "fecha_alta": "2023-01-15",
        "tipo_negocio": "comercial",
        "estado_cuenta": "con_deuda",
        "categoria_cliente": "gold",
        "canal_venta": "mixto",
        "zona_geografica": "sur",
        "telefono": "+54 291 456-7890",
        "email": "aguirre@empresa.com",
        "vendedor": "Ana Martinez",
        "facturacion_anual": 150000
    },    
    {
        "num": "1615",
        "coords": [-38.7184139991519, -62.2767987374334],
        "nombre": "XIANG AIHE",
        "direccion": "VIAMONTE 459",
        "alt": "1100001388",
        "activo": true,
        "fecha_alta": "2023-08-10",
        "tipo_negocio": "particular",
        "estado_cuenta": "al_dia",
        "categoria_cliente": "bronze",
        "canal_venta": "online",
        "zona_geografica": "norte",
        "telefono": "+54 291 789-0123",
        "email": "xiang.aihe@gmail.com",
        "vendedor": "Carlos Rodriguez"
    },
    {
        "num": "550",
        "coords": [-38.7158, -62.2642],
        "nombre": "SUPERMERCADO EL SOL",
        "direccion": "AV. COLON 1250",
        "alt": "1100000234",
        "activo": true,
        "fecha_alta": "2022-11-03",
        "tipo_negocio": "comercial",
        "estado_cuenta": "moroso",
        "categoria_cliente": "vip",
        "canal_venta": "presencial",
        "zona_geografica": "este",
        "telefono": "+54 291 333-4444",
        "email": "admin@superelsol.com",
        "vendedor": "Ana Martinez",
        "facturacion_anual": 280000
    },
    {
        "num": "777",
        "coords": [-38.7401, -62.2897],
        "nombre": "PANADERIA LA ESPIGA",
        "direccion": "MORENO 543",
        "alt": "1100000345",
        "activo": false,
        "fecha_alta": "2021-06-15",
        "tipo_negocio": "comercial",
        "estado_cuenta": "bloqueado",
        "categoria_cliente": "bronze",
        "canal_venta": "telefono",
        "zona_geografica": "oeste",
        "telefono": "+54 291 555-6666",
        "email": "laespiga@bakery.com",
        "vendedor": "Luis Gonzalez"
    }
];

console.log('📄 Clientes cargados:', window.clientesData.length);