[ORIGENDATO]SQL
[SOURCETYPE]ADO
[SERVENAME]marcos\sql2019
#[SERVENAME]miguel\sql2019,1171
#[SERVENAME]desktop-cl1s6os\sql2019,1170
#[SERVENAME]168.196.26.241\sql2019,1170
[USERNAME]ç|
[PWDNAME]]ÅOQVT
[WEBSERVICE]
[PATHDATABASE]
[PWDLEN]6
[USERLEN]2

[SUCURSAL]1
#[INITCATALOGO]nuevasirena
#[INITCATALOGO]montenegro
#[INITCATALOGO]urquiza
#[INITCATALOGO]almacen1810

#[INITCATALOGO]distribuidorakm
#[INITCATALOGO]elsurenio
#[INITCATALOGO]petrocarniceria
#[INITCATALOGO]distribuidoraSUR
#[INITCATALOGO]distMendoza
#[INITCATALOGO]distGattari
#[INITCATALOGO]Surlacteos
#[INITCATALOGO]distSSG
#[INITCATALOGO]danielPereda
#[INITCATALOGO]Quaglia
[INITCATALOGO]AlcarazG

#[SERVENAME]170.81.231.33\sql2014,1170
#[INITCATALOGO]juma

#[INITCATALOGO]nuevasirena2
#[SUCURSAL]2
#[INITCATALOGO]nuevasirena6
#[SUCURSAL]6
#[INITCATALOGO]nuevasirena11
#e[SUCURSAL]11

#[SERVENAME]190.246.80.242\sql2005,1170
#[INITCATALOGO]tapia

#[SERVENAME]klejadistribuidora.ddns.net\sql2014,1170
#[INITCATALOGO]kleja

#[SERVENAME]190.92.109.142\sql2005,1170
#[INITCATALOGO]garrone
#[PWDNAME]}ÅOQVT

#[SERVENAME]marcos\sql2014
#[INITCATALOGO]libreria

#[SERVENAME]marcos\sql2022
#[INITCATALOGO]distmuller

