[ORIGENDATO]SQL
[SOURCETYPE]ADO
[SERVENAME]marcos-hp\sql2022
#[SERVENAME]miguel\sql2019,1171
#[SERVENAME]desktop-cl1s6os\sql2019,1170
#[SERVENAME]168.196.26.241\sql2019,1170
[USERNAME]ç|
[PWDNAME]]ÅOQVT
[WEBSERVICE]
[PATHDATABASE]
[PWDLEN]6
[USERLEN]2

[SUCURSAL]1
#[SERVENAME]lnsgbe.ddnsfree.com\sql2014,1174
#[INITCATALOGO]nuevasirena
#[SERVENAME]montenegro-server\sql2019,1170
#[INITCATALOGO]montenegro
#[INITCATALOGO]almacen1810

[INITCATALOGO]elcalden
#[INITCATALOGO]distribuidorakm
#[INITCATALOGO]elsurenio
#[INITCATALOGO]petrocarniceria

#[INITCATALOGO]distMendoza
#[INITCATALOGO]distGattari
#[INITCATALOGO]Surlacteos
#[INITCATALOGO]distSSG
#[INITCATALOGO]danielPereda
#[INITCATALOGO]AlcarazG
#[INITCATALOGO]MarucaFiam

#[SERVENAME]urquiza-vm,1170
#[INITCATALOGO]urquiza

#[SERVENAME]sur-server\sql2019,1170
#[INITCATALOGO]distribuidoraSUR

#[SERVENAME]quaglia-server\sql2019,1170
#[INITCATALOGO]Quaglia

#[SERVENAME]teo-server\sql2019,1170
#[INITCATALOGO]TeoAutoservicio00
#[SUCURSAL]5
#[INITCATALOGO]TeoMayorista04
#[SUCURSAL]4


#[SERVENAME]170.81.231.33\sql2014,1170
[SERVENAME]juma-server\sql2014,1170
[INITCATALOGO]juma

#[INITCATALOGO]nuevasirena2
#[SUCURSAL]2
#[INITCATALOGO]nuevasirena6
#[SUCURSAL]6
#[INITCATALOGO]nuevasirena11
#e[SUCURSAL]11

#[SERVENAME]marcos\sql2022
#[SERVENAME]190.246.80.242\sql2005,1170
#[INITCATALOGO]tapia

#[SERVENAME]klejadistribuidora.ddns.net\sql2014,1170
#[INITCATALOGO]kleja


#[SERVENAME]garrone-server\sql2005,1170
#[INITCATALOGO]garrone
#[PWDNAME]}ÅOQVT

#[SERVENAME]libreriaesq-server\sql2014,1170
#[INITCATALOGO]libreria
#[SERVENAME]lyris-server\sql2014,1170
#[INITCATALOGO]lyris

#[SERVENAME]lyrisCDP-server\sql2025,1170
#[INITCATALOGO]libreria

#[SERVENAME]alternativa-server\sql2022,1170
#[INITCATALOGO]distmuller
