use gestion
go
delete from maopera
delete from cabefac
delete from cuerfac
delete from cuervari
delete from movstock
delete from existenc
delete from cabeord
delete from cuerord
delete from cuervariord
delete from movctacte
delete from afectacte
delete from movbcocar
delete from afebcocar
delete from afeconcilia
delete from CabeCpra
delete from CuerCpra
delete from TablaImp
delete from RenCtacte
delete from MovCaja
delete from CabeAsi
delete from nmaopera
delete from ncabefac
delete from ncuerfac
delete from ncuervari
delete from pedipda
delete from visita
delete from tablaasi
delete from afenpedido
delete from renflete
delete from fletecarga
delete from fleteplanilla
delete from renmaope
delete from bonictacte
delete from cuervaricpra
delete from cuerruta
delete from caberuta
delete from afeasto
delete from rutavdor
delete from cateibba
execute actualizarid 1
