[ORIGENDATO]SQL
[SOURCETYPE]ADO
[USERNAME]ç|
[PWDNAME]]ÅOQVT
[WEBSERVICE]
[PATHDATABASE]
[SUCURSAL]1
[PWDLEN]6
[USERLEN]2

[SERVENAME]marcos-hp\sql2022
#[SERVENAME]hotel-server\sql2014,1170

[INITCATALOGO]hotel_mu

